version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nestjs}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nestjs}
      POSTGRES_DB: ${POSTGRES_DB:-nestjs_db}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

volumes:
  redis:
  postgres:
